Quantum_Razor_barbershop/urls.py
from django.contrib import admin
from django.urls import path, include
import core.views as views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', views.LandingView.as_view(), name='landing'),
    path('barbershop/', include('core.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib import admin
from django.urls import path
import core.views as views

urlpatterns = [
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('orders/', views.OrdersListView.as_view(), name='orders_list'),
    path('orders/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path("service_create/", views.ServiceCreateView.as_view(), name="service_create"),
    path('review/create/', views.ReviewCreateView.as_view(), name='create_review'),
    path('api/master-info/', views.GetMasterInfoView.as_view(), name='get_master_info'),
    path('order/create/', views.OrderCreateView.as_view(), name='create_order'),
    path('api/master-services/', views.GetServicesByMasterView.as_view(), name='get_services_by_master'),
    # Новые пути для HW46
    path('masters/<int:pk>/', views.MasterDetailView.as_view(), name='master_detail'),
    path('services/', views.ServicesListView.as_view(), name='services_list'),
    path('services/update/<int:pk>/', views.ServiceUpdateView.as_view(), name='service_update'),
]

core/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


class Order(models.Model):
    """Модель заказа."""

    STATUS_CHOICES = [
        ("not_approved", "Не подтвержден"),
        ("moderated", "Прошел модерацию"),
        ("spam", "Спам"),
        ("approved", "Подтвержден"),
        ("in_awaiting", "В ожидании"),
        ("completed", "Завершен"),
        ("canceled", "Отменен"),
    ]

    client_name = models.CharField(max_length=100, verbose_name="Имя клиента")
    phone = models.CharField(max_length=20, verbose_name="Телефон")
    comment = models.TextField(verbose_name="Комментарий", blank=True)
    status = models.CharField(max_length=50, verbose_name="Статус", choices=STATUS_CHOICES, default="not_approved")
    date_created = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания", db_index=True)
    date_updated = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")
    master = models.ForeignKey("Master", on_delete=models.SET_NULL,null=True, blank=True, verbose_name="Мастер")
    services = models.ManyToManyField("Service", verbose_name="Услуги", related_name='orders')
    appointment_date = models.DateTimeField(verbose_name="Дата и время записи")

    def __str__(self):
        return f"Заказ №{self.id} от {self.client_name}"
    
    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"
        ordering = ["-date_created"]
        indexes = [
            # Одиночные  Индексы по имени клиента, номеру телефона и комментарию
            models.Index(fields=["client_name"], name="order_client_name_idx"),
            models.Index(fields=["phone"], name="phone_idx"),
            models.Index(fields=["comment"], name="comment_idx"),
            # Составной индекс по имени клиента и номеру телефона
            models.Index(fields=["client_name", "phone"], name="client_name_phone_idx"),
            # Составной индекс по имени клиента и комментарию
            models.Index(fields=["client_name", "comment"], name="client_name_comment_idx"),
        ]


class Master(models.Model):
    """Модель мастера."""

    first_name = models.CharField(max_length=100, db_index=True)
    last_name = models.CharField(max_length=100)
    photo = models.ImageField(upload_to="images/masters/", blank=True, null=True)
    phone = models.CharField(max_length=20, verbose_name="Телефон")
    address = models.CharField(max_length=255, verbose_name="Адрес")
    experience = models.PositiveBigIntegerField(verbose_name="Стаж", help_text="Опыт работы в годах")
    services = models.ManyToManyField("Service", verbose_name="Услуги", related_name="masters")
    is_active = models.BooleanField(default=True, verbose_name="Активен")
    view_count = models.PositiveIntegerField(default=0, verbose_name="Количество просмотров")

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    class Meta:
        verbose_name = "Мастер"
        verbose_name_plural = "Мастера"
        ordering = ["first_name", "last_name"]
        indexes = [
            # Индек по имени
            models.Index(fields=["first_name"], name="first_name_idx"),
        ]


class Service(models.Model):
    """Модель услуги."""

    name = models.CharField(max_length=200, verbose_name="Название")
    description = models.TextField(verbose_name="Описание", blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    duration = models.PositiveIntegerField(verbose_name="Длительность", help_text="Время выполнения в минутах")
    is_popular = models.BooleanField(default=False, verbose_name="Популярная услуга")
    image = models.ImageField(upload_to="images/services/", blank=True, null=True, verbose_name="Изображение услуги")

    def __str__(self):
        return f'{self.name} - {self.price} руб.'
    
    class Meta:
        verbose_name = "Услуга"
        verbose_name_plural = "Услуги"
        ordering = ["name"]
        indexes = [
            # Индекс по названию
            models.Index(fields=["name"], name="name_idx"),            
        ]


class Review(models.Model):
    """Модель отзыва."""

    text = models.TextField(verbose_name="Текст отзыва")
    client_name = models.CharField(max_length=100, verbose_name="Имя клиента", blank=True)
    master = models.ForeignKey("Master", on_delete=models.CASCADE, verbose_name="Мастер")
    photo = models.ImageField(upload_to="images/reviews/", blank=True, null=True, verbose_name="Фото")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    rating = models.PositiveSmallIntegerField(default=5,
            validators=[
                MinValueValidator(1, message="Рейтинг не может быть меньше 1."),
                MaxValueValidator(5, message="Рейтинг не может быть больше 5.")
            ],
            help_text="Рейтинг от 1 до 5", verbose_name="Оценка")
    is_published = models.BooleanField(default=False, verbose_name="Опубликован")


    def __str__(self):
        return f"Отзыв от {self.client_name} на {self.master}"


    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"
        ordering = ["-created_at"]
        indexes = [
            # Индекс по имени клиента
            models.Index(fields=["client_name"], name="review_client_name_idx"),
        ]

core/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.contrib.admin.views.decorators import staff_member_required
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView
from django.views import View
from .models import *
from django.shortcuts import get_object_or_404, redirect
from django.db.models import Q
from .forms import *
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.contrib.auth.mixins import LoginRequiredMixin  # Добавляем импорт


class StaffRequiredMixin:
    """Миксин для проверки прав staff"""
    @method_decorator(staff_member_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


class LandingView(TemplateView):
    template_name = "core/landing.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            "title_masters": "Наши мастера",
            "masters": Master.objects.prefetch_related('services').filter(is_active=True),
            "title_services": "Наши услуги",
            "services": Service.objects.all(),
            "reviews": Review.objects.filter(is_published=True).select_related('master')[:6]
        })
        return context


class ThanksView(TemplateView):
    template_name = "core/thanks.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        source = self.request.GET.get('source', 'booking')
        context.update({
            'countdown_seconds': 15,
            'redirect_url': reverse('landing'),
            'is_review': source == 'review'
        })
        return context


class OrdersListView(StaffRequiredMixin, ListView):
    model = Order
    template_name = "core/orders_list.html"
    context_object_name = 'orders'
    ordering = ['-date_created']

    def get_queryset(self):
        queryset = super().get_queryset().select_related('master').prefetch_related('services')
        
        search_query = self.request.GET.get('q', '')
        if search_query:
            search_fields = self.request.GET.getlist('search_in', ['name'])
            filters = Q()
            
            if 'name' in search_fields:
                filters |= Q(client_name__icontains=search_query)
            if 'phone' in search_fields:
                filters |= Q(phone__icontains=search_query)
            if 'comment' in search_fields:
                filters |= Q(comment__icontains=search_query)
            
            if filters:
                queryset = queryset.filter(filters)
                
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'КВАНТОВЫЙ ТРЕКЕР ЗАКАЗОВ'
        
        # Получаем список выбранных полей для поиска
        selected_search_fields = self.request.GET.getlist('search_in', [])
        # Если нет выбранных полей (первый заход), устанавливаем только 'name'
        if not selected_search_fields:
            selected_search_fields = ['name']
        
        context['selected_search_fields'] = selected_search_fields
        return context


class OrderDetailView(LoginRequiredMixin, StaffRequiredMixin, DetailView):
    model = Order
    template_name = "core/order_detail.html"
    context_object_name = 'order'
    pk_url_kwarg = 'order_id'


class ServiceCreateView(StaffRequiredMixin, CreateView):
    model = Service
    form_class = ServiceForm
    template_name = 'core/service_create.html'
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создание квантовой услуги'
        return context

    def form_valid(self, form):
        try:
            response = super().form_valid(form)
            messages.success(self.request, f'Услуга {form.cleaned_data["name"]} успешно создана!')
            return response
        except ValidationError as e:
            form.add_error(None, e)
            return self.form_invalid(form)
    
class MasterDetailView(DetailView):
    model = Master
    template_name = 'core/master_detail.html'
    context_object_name = 'master'

    def get_queryset(self):
        return super().get_queryset().prefetch_related('services', 'review_set')

    def get_object(self, queryset=None):
        try:
            master = super().get_object(queryset)
        except Master.DoesNotExist:
            # Обработка 404 для несуществующих мастеров
            return redirect('landing')  # Перенаправление на главную
            
        # Сохраняем просмотренного мастера в сессии
        viewed_masters = self.request.session.get('viewed_masters', [])
        if master.id not in viewed_masters:
            viewed_masters.append(master.id)
            self.request.session['viewed_masters'] = viewed_masters
            
            # Увеличиваем счетчик только один раз за сессию
            Master.objects.filter(pk=master.pk).update(view_count=models.F('view_count') + 1)
            master.refresh_from_db()
        
        return master

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'КВАНТОВЫЙ МАСТЕР: {self.object.first_name} {self.object.last_name}'
        context['master'] = self.object  # Явно передаём объект мастера
        return context

class ServicesListView(StaffRequiredMixin, ListView):
    model = Service
    template_name = 'core/services_list.html'
    context_object_name = 'services'
    ordering = ['name']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'КВАНТОВЫЙ КАТАЛОГ УСЛУГ'
        return context

class ServiceUpdateView(StaffRequiredMixin, UpdateView):
    model = Service
    form_class = ServiceForm
    template_name = 'core/service_update.html'
    success_url = reverse_lazy('services_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'РЕДАКТИРОВАНИЕ УСЛУГИ: {self.object.name}'
        return context

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, f'Услуга "{self.object.name}" успешно обновлена!')
        return response
    
class ReviewCreateView(CreateView):
    model = Review
    form_class = ReviewForm
    template_name = 'core/review_form.html'

    def get_initial(self):
        initial = super().get_initial()
        master_id = self.request.GET.get('master_id')
        if master_id:
            try:
                master = Master.objects.get(pk=master_id)
                initial['master'] = master
            except Master.DoesNotExist:
                pass
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Квантовый отзыв'
        
        # Передаем ID мастера в контекст для отображения в шаблоне
        master_id = self.request.GET.get('master_id')
        if master_id:
            context['selected_master_id'] = master_id
            
        return context

    def form_valid(self, form):
        review = form.save(commit=False)
        review.is_published = False
        review.save()
        return redirect(f"{reverse('thanks')}?source=review")


class GetMasterInfoView(View):
    def get(self, request):
        # Строгая проверка заголовков
        if request.headers.get('X-Requested-With') != 'XMLHttpRequest':
            return JsonResponse({'success': False, 'error': 'Недопустимый запрос'}, status=400)
            
        master_id = request.GET.get('master_id')
        if not master_id:
            return JsonResponse({'success': False, 'error': 'Не указан ID мастера'}, status=400)
            
        try:
            master = Master.objects.get(pk=master_id)
            master_data = {
                'id': master.id,
                'name': f"{master.first_name} {master.last_name}",
                'experience': master.experience,
                'photo': master.photo.url if master.photo else None,
                'services': [{'name': service.name} for service in master.services.all()],
            }
            return JsonResponse({'success': True, 'master': master_data})
        except Master.DoesNotExist:
            return JsonResponse({'success': False, 'error': 'Мастер не найден'}, status=404)


class OrderCreateView(CreateView):
    model = Order
    form_class = OrderForm
    template_name = 'core/order_form.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Квантовая запись'
        return context

    def form_valid(self, form):
        order = form.save(commit=False)
        order.status = 'not_approved'
        order.save()
        form.save_m2m()
        messages.success(self.request, 'Ваша запись успешно создана!')
        return redirect(f"{reverse('thanks')}?source=booking")


class GetServicesByMasterView(View):
    def get(self, request):
        # Строгая проверка заголовков
        if request.headers.get('X-Requested-With') != 'XMLHttpRequest':
            return JsonResponse({'success': False, 'error': 'Недопустимый запрос'}, status=400)
            
        master_id = request.GET.get('master_id')
        if not master_id:
            return JsonResponse({'success': False, 'error': 'Не указан ID мастера'}, status=400)
            
        try:
            master = Master.objects.get(pk=master_id)
            services = master.services.all().values('id', 'name')
            return JsonResponse({'success': True, 'services': list(services)})
        except Master.DoesNotExist:

core/templates/core/landing.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- Секция "О нас" -->
<section id="about">
    <div class="row align-items-center">
        <div class="container py-5">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <h2 class="glow-text mb-4">
                        <i class="fas fa-atom quantum-icon"></i> 
                        КВАНТОВАЯ РЕВОЛЮЦИЯ В БАРБЕРШОПЕ
                    </h2>
                    <div class="quantum-about-card p-4">
                        <p class="quantum-text">Мы — <span class="text-quantum">Quantum Razor</span>, где технологии встречаются с традиционным мастерством.</p>
                        
                        <ul class="quantum-features">
                            <li><i class="fas fa-microchip quantum-feature-icon"></i> Нейросетевые алгоритмы подбора стиля</li>
                            <li><i class="fas fa-clock quantum-feature-icon"></i> Точность до миллиметра и секунды</li>
                            <li><i class="fas fa-flask quantum-feature-icon"></i> Квантовые технологии ухода</li>
                        </ul>
                        
                        <div class="quantum-signature mt-4">
                            <p class="mb-1">— Команда <span class="text-quantum">Quantum Razor</span></p>
                            <div class="quantum-signature-line"></div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="quantum-hologram-effect">
                        <img src="{% static 'images/barber-team.jpg' %}" alt="Наша команда" class="img-fluid rounded-3 quantum-hologram-img">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Секция услуг в две колонки -->
<section id="services" class="my-5">
    <div class="container">
        <h2 class="glow-text text-center mb-4">{{ title_services }}</h2>
        <div class="row row-cols-1 row-cols-md-2 g-4">
            {% for service in services %}
            <div class="col quantum-animate">
                <div class="quantum-order-card h-100 p-3">
                    <div class="d-flex align-items-center">
                        <i class="fas fa-wrench quantum-icon me-3 fs-4"></i>
                        <div>
                            <h5 class="glow-text mb-1">{{ service.name }}</h5>
                            <p class="mb-0 text-quantum">{{ service.price }} руб.</p>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<!-- Инклюд блока мастеров -->
<section id="masters" class="my-5">
    <div class="container">
        <h2 class="glow-text text-center mb-4">{{ title_masters }}</h2>
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 g-4">
            {% include "core/includes/masters_cards_include.html" %}
        </div>
    </div>
</section>

<!-- Инклюд блока отзывов -->
<section id="reviews" class="my-5">
    <div class="container">
        <h2 class="glow-text text-center mb-4">Квантовые отзывы</h2>
        <div class="row g-4">
            {% include "core/includes/reviews_cards_include.html" %}
        </div>
    </div>
</section>

<!-- Секция записи -->
<section id="booking">
    <div class="quantum-booking-cta">
        <div class="container text-center py-4">
            <div class="d-flex flex-column flex-md-row justify-content-center align-items-center">
                <h3 class="glow-text mb-3 mb-md-0 me-md-4">
                    <i class="fas fa-calendar-alt quantum-icon me-2"></i>
                    ГОТОВЫ К КВАНТОВОМУ ПРЕОБРАЖЕНИЮ?
                </h3>
                <a href="{% url 'create_order' %}" class="btn btn-quantum-pulse">
                    ЗАПИСАТЬСЯ СЕЙЧАС
                </a>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

core/templates/core/master_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container quantum-detail">
    <h1 class="glow-text">{{ title }}</h1>
    <div class="quantum-card">
        <div class="quantum-master-header">
            {% if master.photo %}
            <img src="{{ master.photo.url }}" class="quantum-master-photo">
            {% else %}
            <div class="quantum-master-photo-placeholder">
                <i class="bi bi-person-circle"></i>
            </div>
            {% endif %}
            <div class="quantum-master-info">
                <h2>{{ master.first_name }} {{ master.last_name }}</h2>
                <p><i class="bi bi-award"></i> Стаж: {{ master.experience }} лет</p>
                <p><i class="bi bi-eye"></i> Просмотров: {{ master.view_count }}</p>
                <p><i class="bi bi-telephone"></i> {{ master.phone }}</p>
                <p><i class="bi bi-geo-alt"></i> {{ master.address }}</p>
            </div>
        </div>

        <div class="quantum-section">
            <h3 class="quantum-section-title glow-text-sub">Квантовые услуги мастера</h3>
            <ul class="quantum-services-list">
                {% for service in master.services.all %}
                <li class="quantum-service-item">
                    <i class="bi bi-scissors"></i> {{ service.name }} - {{ service.price }} руб.
                </li>
                {% empty %}
                <li class="quantum-service-item">У мастера пока нет услуг</li>
                {% endfor %}
            </ul>
        </div>

        <div class="quantum-section">
            <h3 class="quantum-section-title glow-text-sub">Квантовые отзывы</h3>
            <div class="quantum-reviews-grid">
                {% for review in master.review_set.all %}
                    {% if review.is_published %}
                    <div class="quantum-review-card mb-3">
                        <div class="quantum-review-header">
                            <span class="quantum-review-name">{{ review.client_name }}</span>
                            <span class="quantum-review-rating">
                                {% for i in "12345" %}
                                    {% if forloop.counter <= review.rating %}
                                        <i class="bi bi-star-fill"></i>
                                    {% else %}
                                        <i class="bi bi-star"></i>
                                    {% endif %}
                                {% endfor %}
                            </span>
                        </div>
                        <div class="quantum-review-body">
                            <p class="quantum-review-text">{{ review.text }}</p>
                            {% if review.photo %}
                            <img src="{{ review.photo.url }}" class="quantum-review-photo">
                            {% endif %}
                        </div>
                    </div>
                    {% endif %}
                {% empty %}
                <p class="quantum-no-reviews">Пока нет опубликованных отзывов</p>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

core/templates/core/order_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- Детали заказа -->
{% include "core/includes/order_card_include.html" %}
{% endblock %}

core/templates/core/order_form.html
<!-- core/templates/core/order_form.html -->
{% extends "base.html" %}
{% load static %}

{% block content %}
<div id="data_div" 
    data-services-url="{% url 'get_services_by_master' %}"
    style="display: none;">
</div>

<section class="quantum-main">
    <div class="container py-5">
        <div class="quantum-about-card p-4 mx-auto" style="max-width: 700px;">
            <h2 class="glow-text text-center mb-4">
                <i class="fas fa-calendar-plus quantum-icon"></i>
                {{ title }}
            </h2>
            
            <form method="POST" class="quantum-form" id="order-form">
                {% csrf_token %}
                
                <!-- Выбор мастера -->
                <div class="mb-4">
                    <label class="glow-text quantum-label">
                        <i class="fas fa-user-cog me-2"></i>Выберите мастера
                    </label>
                    {{ form.master }}
                    <div id="master-info" class="mt-3"></div>
                </div>

                <!-- Выбор услуги (изначально скрыт) -->
                <div class="mb-4" id="services-section" style="display: none;">
                    <label class="glow-text quantum-label">
                        <i class="fas fa-scissors me-2"></i>Выберите услуги
                    </label>
                    <div id="services-container" class="quantum-scrollbar">
                    </div>
                </div>

                <!-- Имя клиента -->
                <div class="mb-4">
                    <label class="glow-text quantum-label">
                        <i class="fas fa-user me-2"></i>Ваше имя
                    </label>
                    {{ form.client_name }}
                </div>

                <!-- Телефон -->
                <div class="mb-4">
                    <label class="glow-text quantum-label">
                        <i class="fas fa-phone me-2"></i>Телефон
                    </label>
                    {{ form.phone }}
                </div>

                <!-- Дата и время записи -->
                <div class="mb-4">
                    <label class="glow-text quantum-label">
                        <i class="fas fa-clock me-2"></i>Дата и время записи
                    </label>
                    {{ form.appointment_date }}
                </div>

                <!-- Комментарий -->
                <div class="mb-4">
                    <label class="glow-text quantum-label">
                        <i class="fas fa-comment me-2"></i>Комментарий (необязательно)
                    </label>
                    {{ form.comment }}
                </div>

                <div class="text-center mt-5">
                    <button type="submit" class="btn btn-quantum-pulse px-5">
                        <i class="fas fa-paper-plane me-2"></i>Создать квантовую запись
                    </button>
                </div>
            </form>
        </div>
    </div>
</section>
{% endblock content %}

{% block extra_js %}
<script src="{% static 'js/order_form.js' %}"></script>
{% endblock extra_js %}

core/templates/core/service_update.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container quantum-form-container">
    <h1 class="glow-text">{{ title }}</h1>
    
    <form method="post" enctype="multipart/form-data" class="quantum-form">
        {% csrf_token %}
        
        <div class="quantum-form-grid">
            <div class="quantum-form-column">
                <div class="quantum-form-group">
                    <label for="id_name">Название услуги</label>
                    {{ form.name }}
                    {% if form.name.errors %}
                    <div class="quantum-form-error">{{ form.name.errors }}</div>
                    {% endif %}
                </div>
                
                <div class="quantum-form-group">
                    <label for="id_price">Цена (руб.)</label>
                    {{ form.price }}
                    {% if form.price.errors %}
                    <div class="quantum-form-error">{{ form.price.errors }}</div>
                    {% endif %}
                </div>
                
                <div class="quantum-form-group">
                    <label for="id_duration">Длительность (мин.)</label>
                    {{ form.duration }}
                    {% if form.duration.errors %}
                    <div class="quantum-form-error">{{ form.duration.errors }}</div>
                    {% endif %}
                </div>
                
                <div class="quantum-form-group quantum-checkbox-group">
                    {{ form.is_popular }}
                    <label for="id_is_popular">Популярная услуга</label>
                </div>
            </div>
            
            <div class="quantum-form-column">
                <div class="quantum-form-group">
                    <label for="id_image">Изображение услуги</label>
                    {% if form.instance.image %}
                    <div class="quantum-image-preview">
                        <img src="{{ form.instance.image.url }}" alt="Текущее изображение">
                    </div>
                    {% endif %}
                    {{ form.image }}
                    {% if form.image.errors %}
                    <div class="quantum-form-error">{{ form.image.errors }}</div>
                    {% endif %}
                </div>
            </div>
        </div>
        
        <div class="quantum-form-group">
            <label for="id_description">Описание услуги</label>
            {{ form.description }}
            {% if form.description.errors %}
            <div class="quantum-form-error">{{ form.description.errors }}</div>
            {% endif %}
        </div>
        
        <div class="quantum-form-actions">
            <button type="submit" class="quantum-button">
                <i class="bi bi-save"></i> Сохранить квантовые изменения
            </button>
            <a href="{% url 'services_list' %}" class="quantum-button quantum-button-cancel">
                <i class="bi bi-x-circle"></i> Отмена
            </a>
        </div>
    </form>
</div>
{% endblock %}